print('*'*50)
a = int(input('Enter the value of a: '))
m = int(input('Enter the value of m: '))
n = int(input('Enter the value of n: '))
output = (a**m)/(a**n)
print('='*70)
print(f'\t\t logic 1: (a**m)/(a**n) ---> ({a}**{m})/({a}**{n}) = {output}')
print(f'\t\t logic 2: a**(m-n) ---> {a}**({m}-{n}) = {output}')
print('='*70)
