print('#'*150)
print("\t\t 10. Write a Python Program to print a given Number in reverse order")
print('#'*150)
n = int(input("Enter the Number: "))
s = str(n)
print('#'*150)
output = int(s[::-1])
print('\t\t\t\t Original Number ={}'.format(n))
print(f'\t\t\t\t Reversed Number = {output}')
print('#'*150)
